- CONTRIBUTORS.md
- LICENSE.txt
- MANIFEST.in
- README.rst
- circle.yml
- setup.cfg
- setup.py
- spyder_reports/__init__.py
- spyder_reports/reportsplugin.py
- spyder_reports/tests/__init__.py
- spyder_reports/widgets/__init__.py
- spyder_reports/widgets/reportsgui.py
> PR: Basic template

- setup.cfg
- setup.py
- spyder_reports/__init__.py
- spyder_reports/_version.py
- spyder_reports/reportsplugin.py
- spyder_reports/widgets/reportsgui.py
- ~add versioneer~ remove versioneer
- add basic methods
- add empty widget
> PR: Create empty widget

- README.md
- setup.py
- spyder_reports/reportsplugin.py
- spyder_reports/widgets/reportsgui.py
Fixes: #11
There's some things missing, but It's rendering reports 😄
> PR: Pweave support

- README.rst
- circle.yml
- requirements.txt
- setup.cfg
- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
- spyder_reports/widgets/reportsgui.py
> PR: Activate continuous integration

- spyder_reports/reportsplugin.py
- spyder_reports/widgets/reportsgui.py
- spyder_reports/widgets/tests/test_report_widget.py
> PR: Tabs each file

- README.rst
Remove unneeded badges and fix formatting.
> PR: Improve Readme

- .ciocheck
- ci/install.sh
- circle.yml
- setup.py
- spyder_reports/reportsplugin.py
- spyder_reports/utils/__init__.py
- spyder_reports/utils/welcome.md
- spyder_reports/widgets/reportsgui.py
- spyder_reports/widgets/tests/test_report_widget.py
> PR: Add some content to welcome and improve CI

- .coveragerc
- ci/install.sh
- requirements.txt
- setup.cfg
- setup.py
- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
Fixes #26 
Deactivate plugin in python2, and make it depend of spyder3.2
(We will need to wait until spyder3.2 release to CI to work, or install spyder from git)
> PR: Add check compability

- ci/install.sh
We need to use the right package manager for each Circle node, like this
* Node 0: pip
* Node 1: conda
> PR: Install Spyder with pip on first CircleCI node

- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
Fixes #27.
See https://github.com/spyder-ide/spyder-reports/issues/27#issuecomment-315773535
> PR: Render report in a thread.

- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
> PR: Fix error with error messagebox

- README.rst
- ci/install.sh
https://github.com/spyder-ide/spyder-reports/issues/27#issuecomment-317059351
> PR: Add pandoc as a dependency in our tests

- spyder_reports/reportsplugin.py
> PR: Remove unnecessary reloading of welcome file output

- spyder_reports/reportsplugin.py
> PR: Use Spyder's temp directory to render our welcome file

- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
- spyder_reports/widgets/reportsgui.py
- spyder_reports/widgets/tests/test_report_widget.py
> PR: Disambiguate tabs

- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
> PR: Render reports in a temp dir

- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
- spyder_reports/widgets/reportsgui.py
> PR: Show render progress and errors

- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
- spyder_reports/utils/__init__.py
- spyder_reports/utils/welcome.md
- spyder_reports/widgets/reportsgui.py
- spyder_reports/widgets/tests/test_report_widget.py
Fixes #43 
Add a tooltip menu, and also tab menu actions(rightclick over tabs)
> PR: Save reports to disk

- README.rst
- circle.yml
- setup.cfg
- setup.py
- spyder_reports/reportsplugin.py
- spyder_reports/tests/test_plugin.py
> Add python2 support

- .gitignore
- README.rst
- circle.yml
- setup.py
- spyder_reports/tests/test_plugin.py
Some miscellaneous fixes for 0.1.1 release
Fixes #53 
Fixes #54 
Remove and regenerate coveralls badge, add it to circle CI setup
> PR: Misc fixes
